name: cd

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploys
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25.1"

      - name: Build app
        run: gcloud builds submit --tag us-south1-docker.pkg.dev/notely-497203/notely-ar-repo/sha256:717fa11b207140e92ab97a516c1ec560c98c51e6c73dfc41ea47c22acf73bd30
        
  serviceAccount:
    name: set-up gcloud
    runs-on: ubuntu-latest
    steps:
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v3'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'
