name: cd

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25.1"

      - name: Build app
        run: ./scripts/buildprod.sh
        
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v3'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      - name: Build app
        run: gcloud builds submit --tag us-south1-docker.pkg.dev/notely-497203/notely-ar-repo/sha256:717fa11b207140e92ab97a516c1ec560c98c51e6c73dfc41ea47c22acf73bd30

      - name: Deploy to Cloud Run
        run: gcloud run deploy notely --image us-central1-docker.pkg.dev/notely-497203/notely-ar-repo/sha256:5f05dc209fe93949a6483885023cd482f9a13eb3da47e6a5d6b931a6ce652d30 --region us-central1 --allow-unauthenticated --project notely-497203 --max-instances=4
